### ISSUE TITLE
Crash with scroll wheel responses

### ISSUE THREAD

**Issue by avaidyam** [BIDMCDigitalPsychiatry/LAMP-app#3]
Seems to occur on all Android devices with scroll wheel (list) responses. Please confirm.

**Comment by michaelmenon** [comment]
This android  issue was fixed in our android beta version.So we have moved this to production now.

The 'Mind Lamp' version 1.0.17 app has been submitted to the Google Play Store [This may take several hours to become live].  Will update the code asap.

**Comment by avaidyam** [comment]
I'm currently testing the beta and still encounter a progress wheel that never progresses to the next screen.

**Comment by michaelmenon** [comment]
Please let me know your device type and OS version.

**Comment by avaidyam** [comment]
Google Pixel, Android 10.

**Comment by michaelmenon** [comment]
Can you please test the latest Google play store app after deleting the old build and see if you can reproduce.

**Comment by avaidyam** [comment]
It seems to work now!
